# .github/workflows/manual_deploy.yml
name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Stage (dev|test|prod)'
        required: true
        default: 'dev'

env:
  hostname_dev: dev-api.gemeindeonline.ch
  key_filename: id_admin@5.101.123.4-external
  deployer_url: https://deployer.org/releases/v7.0.0-beta.25/deployer.phar

jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    
    environment:
        name: dev
        url: "https://${{ env.hostname_dev }}"

    steps:
      - uses: actions/checkout@v2
    
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      - name: Check dependencies for known vulnerabilities
        uses: symfonycorp/security-checker-action@v2
        
      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan ${{ env.hostname_dev }} >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.ADMIN_5_101_123_4_PRIVATE_KEY }}" > /home/runner/.ssh/${{ env.key_filename }}
          chmod 600 /home/runner/.ssh/${{ env.key_filename }}
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
          ssh-add /home/runner/.ssh/${{ env.key_filename }}

      - name: Download Deployer
        run: |
          wget -O deployer.phar ${{ env.deployer_url }}
          chmod +x deployer.phar
  
      - name: Deploy to host
        run: |
          php deployer.phar deploy stage=${{ github.event.inputs.stage }}
