# .github/workflows/manual_deploy.yml
name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'Deploy Environment'
        required: true
        default: 'dev'

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    
    environment:
        name: dev
        url: https://dev-api.gemeindeonline.ch

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          tools: composer:v2, deployer

      - name: Deploy
        uses: deployphp/action@master
        with:
          private-key: ${{ secrets.ADMIN_5_101_123_4_PRIVATE_KEY }}
          known-hosts: ${{ secrets.KNOWN_HOSTS_5_101_123_4 }}
          dep: deploy ${{ github.event.inputs.deploy_env }} -v
